routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home', function () {
    return view('home');
});

Route::get('/', function () {
    return view('auth.login');
});

//Administrador
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/administrador', function () {
     return view('Administrador.Dashboard');
     
 });
 
 Route::resource('administrador','AdminController');

});

//Tickets
Route::get('/ticket/create','TicketController@create');
Route::post('/ticket','TicketController@store');
Route::get('/tickets','TicketController@index');



Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    public function tickes()
    {
        return $this->hasMany(ticket::class);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ticket extends Model
{
    protected $fillable=[
        'problema',
        'descripcion',
        'estado',

    ];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admincontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ticket;

class Admincontroller extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = ticket::all();
        return view('Administrador.Dashboard', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = ticket::find($id);
        return view('Administrador.Edit', compact('data'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'estado'=>'required'
        ]);

        $data = ticket::find($id);
        $data->estado=$request->estado;
        $data->save();

        return redirect('/administrador')->with('Genial', 'Revisado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\ticket;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = ticket::where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();
        return view('tickets.Vista', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tickets.Crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'problema' => 'required',
            'descripcion' => 'required',
          ]);
        $data = new ticket;
        $data->user_id = auth()->id();
        $data->problema=$request->problema;
        $data->descripcion=$request->descripcion;
        $data->save();

        return redirect('/tickets');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(ticket $ticket)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ticket $ticket)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(ticket $ticket)
    {
        //
    }
}

resources/views/Administrador/Dashboard.blade.php
@extends('layouts.app')

@section('content')

@extends('Menus.MenuAdmin')

<br>

    <div class="container table-responsive">
        <table class="table table-striped table-bordered table-hover">
  
    <tr>
<th>#Nodo</th>
<th>Problema</th>
<th>Descripcion</th>
<th>Estado</th>
<th>Fecha de Creacion</th>
<th>Resolver</th>
      </tr>
@foreach ($tickets as $key=>$data)
<tr>
<td>{{++$key}}</td>

<td>{{$data->problema}}</td>
<td>{{$data->descripcion}}</td>
<td>{{$data->estado}}</td>
<td>{{$data->created_at}}</td>
<td><a class="btn btn-success" style="background: #69bb85!important; border-color:#69bb85!important;" href="{{action('AdminController@edit', $data->id)}}">Resolver </a></td>
</tr>
@endforeach
        </table>
    </div>
        @endsection

resources/views/Administrador/Edit.blade.php
@extends('layouts.app')

@section('content')

@extends('Menus.MenuAdmin')

<div class="container mt-5">
<form method="post" action="{{ route('administrador.update', $data->id) }}">
    @method('PATCH') 
    @csrf
    <div class="form-group">

        <label for="first_name">Problema:</label>
        <input type="text" class="form-control" disabled value={{ $data->problema}} />
    </div>

    <div class="form-group">
        <label for="last_name">Descripcion:</label>
        <input type="text" class="form-control" disabled value={{ $data->descripcion }} />
    </div>

    <div class="form-group">
        <label for="last_name">Estado:</label>
        <select id="inputState" class="form-control" name="estado">
            <option value="Via Remota">Via Remota</option>
            <option value="Presencial">Presencial</option>
          </select>
    </div>
   
    <button type="submit" class="btn btn-primary" style="background: #69bb85!important; border-color:#69bb85!important;">Actualizar</button>
</form>
</div>
@endsection

resources/views/Menus/MenuAdmin.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    Administrador
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="nav navbar-nav ml-auto">
         @if (Auth::check())
         <li class="nav-item active m-2">
                {{ auth()->user()->name}}
         </li>
         <li class="nav-item m-2">
             {{ auth()->user()->email}}
         </li>
         <li class="nav-item m-2">
             <a href="{{ url('/logout') }}"> logout </a>
         </li>
         @endif
       </ul>
     </div>
   </nav>

resources/views/Menus/MenuUsuario.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    @if (Auth::check())
   {{ auth()->user()->name}}
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="nav navbar-nav ml-auto">
        
         
         <li class="nav-item m-2">
             {{ auth()->user()->email}}
         </li>
         <li class="nav-item m-2">
             <a href="{{ url('/logout') }}"> logout </a>
         </li>
         @endif
       </ul>
     </div>
   </nav>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<form action="/ticket/create" method="GET" enctype="multipart/form-data">
    @csrf
<button type="submit" class="btn btn-primary btn-lg" >
    Generar Ticket
</form>        
<br>
<button type="submit" class="btn btn-primary btn-lg" ><a href="{{ url('/logout') }}"> logout </a>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>
<body>
    <div id="app">


        <main >
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/tickets/Crear.blade.php
@extends('layouts.app')

@section('content')

@extends('Menus.MenuUsuario')

<div class="container mt-5">
<form action="/ticket" method="POST" >
@csrf
    <div class="form-group">
      <label for="exampleInputEmail1">Problema:</label>
      <input type="text" class="form-control" name="problema" placeholder="Menciona tu problema"> 
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1" >Descripcion del problema:</label>
        <textarea class="form-control" name="descripcion" style="resize: none; overflow: auto;"></textarea>
      </div>
    
    <button type="submit" class="btn btn-primary">Crear Ticket</button>
  </form>
</div>
@endsection

resources/views/tickets/Vista.blade.php
@extends('layouts.app')

@section('content')

@extends('Menus.MenuUsuario')
<div class=" container table-responsive mt-5 ">
<form action="/ticket/create" method="GET" enctype="multipart/form-data">
        @csrf
    <button type="submit" class="btn btn-primary btn-lg" >
        Generar Ticket
    </button>
    </form>

   
      <table class="table table-striped table-bordered table-hover mt-1">
   
    <tr>
<th>#Nodo</th>
<th>Problema</th>
<th>Descripcion</th>
<th>Estado</th>
<th>Fecha de Creacion</th>
      </tr>
@foreach ($tickets as $key=>$data)
<tr>
<td>{{++$key}}</td>
<td>{{$data->problema}}</td>
<td>{{$data->descripcion}}</td>
<td>{{$data->estado}}</td>
<td>{{$data->created_at}}</td>
</tr>
@endforeach
        </table>
    </div>
@endsection